a = int(input("1st number: "))
b = int(input("2nd number: "))
print("Sum: " + str(a + b))
print("Difference: " + str(a - b))
print("Product: " + str(a * b))
print("Power: " + str(a ** b))
print("Quotient (int): " + str(a // b))
print("Quotient (float): " + str(a / b))
print("Remainder: " + str(a % b))
