w = int(input("Enter width: "))
s = float(input("Enter squat: "))
p = float(input("Enter bench press: "))
d = float(input("Enter deadlift: "))
print("#"*w)
print("# Powerlifting 2022W", end=" "*(w-21) + "#" + '\n')
print("#"*w)
print("Maximum squat:" + " "*(w-16-len(str(s))) + str(s) + "kg")
print("Maximum Bench Press:" + " "*(w-22-len(str(p))) + str(p) + "kg")
print("Maximum Deadlift:" + " "*(w-19-len(str(d))) + str(d) + "kg")
print("-"*w)
print("Total:" + " "*(w-8-len(str(s + p + d))) + str(s + p + d) + "kg")
